### ISSUE TITLE
When an approver approves a pending stage in the pipeline, can a pipeline get access to the approver + comment in a variable?

### ISSUE THREAD

**Issue by bitsofinfo** [MicrosoftDocs/vsts-docs#7512] opened 2020-03-06 00:02 UTC
When an approver approves a pending stage in the pipeline, can a pipeline get access to the approver + comment in a variable?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b067a175-f640-7503-9c1e-f0130c6dbeda
* Version Independent ID: ff743c7b-a103-eae6-4478-62ba995a4b36
* Content: [Pipeline deployment approvals - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/approvals?view=azure-devops&tabs=check-pass)
* Content Source: [docs/pipelines/process/approvals.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/approvals.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **shashban**

**Comment by WilliamAntonRohm** [comment] 2020-03-06 20:58
Near-duplicate of #7511 -- added the comment above to that issue.

**Closed by WilliamAntonRohm** 2020-03-06 20:58 UTC
Labels: Pri1, cba, devops-cicd-process/tech, devops/prod, duplicate
