### ISSUE TITLE
WIQL samples in tables aren't rendering correctly

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#1265] opened 2018-07-10 21:15 UTC
The "Include these query clauses" columns appear to be using triple backticks and some underscores that aren't rendering correctly on the doc site or GH

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0efcf77b-29e3-61fe-2dfb-cbea0561e720
* Version Independent ID: e17b1af0-a501-9bf7-53ee-94492479c06b
* Content: [Query by account, user name, workflow or board changes - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/track/query-by-workflow-changes?view=vsts#query-by-kanban-board-changes)
* Content Source: [docs/work/track/query-by-workflow-changes.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/work/track/query-by-workflow-changes.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment] 2018-07-12 17:10
@nschonni - Thank you for the feedback. I'm not seeing any issue viewing in Chrome or Edge. Can you be more specific as to what the format issue is?

**Comment by nschonni** [comment] 2018-07-12 17:15
I think maybe i'm getting confused by the use of `_` in the code blocks

**Comment by KathrynEE** [comment] 2018-07-17 00:39
@nschonni - OK. I'm closing this as the underscores are in the code syntax by design.

**Closed by KathrynEE** 2018-07-17 00:39 UTC
