### ISSUE TITLE
print link

### ISSUE THREAD

**Issue by zahirtezcan-bugs** [MicrosoftDocs/vsts-docs#2486] opened 2018-11-19 12:16 UTC
where is your frakking print link in this documentation site.

thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis in Azure DevOps and TFS - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=vsts#feedback)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment] 2018-11-19 16:58
Hi @zahirtezcan-bugs, select **Download PDF** at the bottom left of your screen. Then, the print option will be available to you. Please let us know if you continue to have difficulties. Thank you!

**Comment by zahirtezcan-bugs** [comment] 2018-11-19 20:51
I know I can download that huge document containing all the pages from a big tree. But, I just need this page of documentation to move around. Additionally, imagine that I am using a mobile phone and I just want to send this page to a printer in the vicinity instead of downloading that pdf via my cell plan.

**Comment by chcomley** [comment] 2018-11-19 22:43
@zahirtezcan-bugs You could save the page or print straight from the browser. Depending on the browser you're using, if you don't see a print icon, choose the ellipses beneath your window close **x**. Hope that helps.

**Comment by zahirtezcan-bugs** [comment] 2018-11-22 04:12
The point of the issue is not "the browser window" and not "mobile device". It is not having a "print link" in a documentation site. This is an issue in the sense that you do not have special css/page style for printing.

When I try to print a page it takes TOC as columns and the content is printed on 1/3 of a page in an unreadable manner. This also cause some of the pages do not print well with comments. Just check out "https://www.codeproject.com/". That site is there for Windows or .Net developers for decades and always has print link in (ergo printing style for) their documents/articles.

MSDN used to have bad looking but really good to use styles. For like last 8 years VS documentation is going under overhauls with each VS version. It looks better and better. But usability gets worse everytime. I need refreshing my documentation with VS version so I will refer to them by VS2017 etc.:

 - First and foremost there is no documentation download (no i am not talking about downloading PDFs) for VisualStudio help viewer. Not even for MSDN subscribers. This was a blessing for enterprises working in a no-internet environment. There was a tool by someone (non-microsoft) for documentation download and it is not working with VS2017 docs anymore. We are downloading with a machine connected to internet and copying data under "C:\ProgramData\...". I mean WTF.
- Since VS HelpViewer has nice indexing and easy to navigate (tree) options I always preferred it over web pages. And particularly when I press F1 button in VS it opens me a HelpViewer. For VS2017 pages inside HelpViewer are not only bad (in terms of usability) but also looks much worse than original MSDN documentation. I assume that there are some page styles getting downloaded from Internet that we do not have.
    > About bad usability, if you take .NET framework class documentation, there are no options to hide overriden functionality anymore. This way some classes (especially WPF framework) are impossible to understand.

- Especially because the help-viewer is almost not usable anymore, newcomers are trying to use your website and they need printing some classes or some specific documentation. But printed content looks like garbage. And I mean it.

I am currently finding myself using "go to definition" in VisualStudio instead of documentation.

I have created the issue and you closed immediately after you commented about it. That really pissed me off TBH. Because it signals me that you are a person to process issues for a living and do not care about the product or the people. Same old Microsoft it seems.

**Comment by chcomley** [comment] 2018-11-22 04:32
@zahirtezcan-bugs I'm sorry this experience has been upsetting for you. Please accept my sincerest apologies. I've reopened this issue and notified my team.

**Comment by erickson-doug** [comment] 2018-11-22 05:34
@kubeaver @ShevaDas can you respond here?

**Comment by ShevaDas** [comment] 2018-11-27 20:56
@zahirtezcan-bugs Apologies if I'm misunderstanding your issue, but we do have a print.css in place and when I hit ctrl+p on the [page you filed this issue on](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=vsts#feedback), it displays fine on my end. Would you be able to provide a screenshot of what it looks like to you?

**Comment by zahirtezcan-bugs** [comment] 2018-11-27 21:39
This is what I get from my home in a print preview of the page:
![print-preview](https://user-images.githubusercontent.com/37615095/49112843-e24c2700-f2a4-11e8-862d-1536d246d94b.png)

Things got a little more funny when I tried to print this section from "Download PDF" option at work. At the creation time of the issue the section started at page 79 (now it is at 81). If I had printed from 79 to the end of the section, then I'd got all the chars garbled like kerning issue all over the place. If I printed a larger portion of the document then I printed fine. I'll check later if I can find the PDF.

**Comment by ShevaDas** [comment] 2018-11-30 22:14
@zahirtezcan-bugs I'm sorry, I can't reproduce your issue with the print or PDF download. Can you provide more details about what operating system and browser you're using?

**Comment by zahirtezcan-bugs** [comment] 2018-12-01 06:19
Windows 10 and Firefox. It could be seen on the screenshot though anyway.

This is the screenshot from original pdf:

![original](https://user-images.githubusercontent.com/37615095/49324928-8e15a100-f549-11e8-8ab9-e0eedcfbbefb.png)

This is what I do when I try to print a portion of the PDF. Please ignore "Microsoft Print To PDF" device. It is for the showcase here. I get same thing when I actually print to the paper:

![81-96](https://user-images.githubusercontent.com/37615095/49324897-10519580-f549-11e8-811d-b03c80eb3cf6.png)

This is somehow what I get:

![less-garbled](https://user-images.githubusercontent.com/37615095/49324929-966ddc00-f549-11e8-8965-4ef0b26b7220.png)

You may say that "I can read this". Well, I can too. But this is a far better version thah I got at the time of the issue creation. But, that time I needed to start from page 79 instead of 81. Some content is added before the specified page and it somehow fixed the body text. But not the titles or layout. 

In the end the issue may go into the usual case of "picture or it didn't happen".

**Comment by shirgoldbird** [comment] 2019-01-16 00:45
@zahirtezcan-bugs I've tried to repro this several times and haven't been able to—my apologies! If you're still seeing the error, I can keep trying; otherwise, I'd like to close this out.

**Comment by zahirtezcan-bugs** [comment] 2019-01-16 05:06
So, in Firefox you can print more than one page and when you print-to-pdf you get no alignment or kerning issues. **If** that is the case feel free to close this.

**Comment by shirgoldbird** [comment] 2019-01-17 23:33
@zahirtezcan-bugs I was just able to repro [this portion](https://github.com/MicrosoftDocs/vsts-docs/issues/2486#issuecomment-442227205) of your issue so I'll pass that one along to our engineering team.

**Comment by shirgoldbird** [comment] 2019-02-20 00:03
@zahirtezcan-bugs Our engineering team has put in a fix for this—please take a look and close this issue out if it's working properly.

**Comment by zahirtezcan-bugs** [comment] 2019-02-20 18:29
Current implementation looks a lot nicer for readabilty. But still has problems within .NET class documentation. Some of the property descriptions gets hidden on bottom/top of pages.

Following image is taken from print-preview in Firefox for WPF TextBox class page (https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.textbox?view=netframework-4.7.2)

![textbox-propertyglitch](https://user-images.githubusercontent.com/37615095/53115080-4e61c280-3556-11e9-845b-9ec034174a2a.png)

**Comment by shirgoldbird** [comment] 2019-03-01 21:44
@zahirtezcan-bugs In Firefox, using print to PDF shows this for me:

![image](https://user-images.githubusercontent.com/3937986/53668136-d9fae380-3c27-11e9-8da3-475f3cb0c0ac.png)

Are you printing differently? Otherwise I'm not able to reproduce it.

**Comment by zahirtezcan-bugs** [comment] 2019-03-01 23:00
I had that picture from my workplace.

I have tried this at home now, the page seems fine for printing at the moment. I have also checked out some of page(s) I frequently visit and they seem fine too.

I will check my office computer and let you know if that is working too.

**Comment by zahirtezcan-bugs** [comment] 2019-03-04 06:29
It seems working in the office space too. Thanks for all the patience and good work.

**Comment by shirgoldbird** [comment] 2019-03-05 00:00
Glad everything is working!

**Comment by shirgoldbird** [comment] 2019-03-05 00:01
@chcomley could you please close this?

**Closed** 2019-03-05 02:14 UTC
