### ISSUE TITLE
requirements.txt's dependencies are not installed in App Service

### ISSUE THREAD

**Issue by HK-Zhang** [MicrosoftDocs/vsts-docs#5545] opened 2019-09-10 13:00 UTC
my project has a dependency on SQLAlchemy. it is listed in requirements.txt. after deployed my service failed to run due to missing module of SQLAlchemy. 

how to manually install requirements.txt in Azure Devops?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eefdcb17-b1e5-141c-aef8-36795c9983af
* Version Independent ID: 007ebfcf-12bf-755c-858b-540d0fc59f96
* Content: [Build and deploy Python web apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/python-webapp?view=azure-devops#feedback)
* Content Source: [docs/pipelines/ecosystems/python-webapp.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/python-webapp.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by msebolt** [comment] 2019-09-11 00:10
@HK-Zhang Thank you for the question.

You can try using the [Python script task](https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/python-script?view=azure-devops) with something like:

```
pip3 install -r requirements.txt
```

If this is not what you had in mind please comment below.

**Comment by HK-Zhang** [comment] 2019-09-11 01:14
@msebolt, where should I put this script: pip3 install -r requirements.txt ? 
I put it as a post-deployment script. I'll get permission denied issue when running the pipeline.

**Comment by msebolt** [comment] 2019-09-11 16:01
Re-assigning to the author.

**Comment by jxjia** [comment] 2019-09-28 13:49
This problem has been repeating, your Build pipeline does NOT automatically installs dependencies during deployment (i.e. a missing pip install -r requirements.txt step). I wonder how is this not catered in the Azure Pipeline's deployment process wheras the az webapp up command does ?
By the way, the article itself is awecome! Great contents and adequate explanation. Way to go team !

**Comment by kraigb** [comment] 2019-10-02 20:49
Thanks everyone; I'm looking into what's needed here.

**Comment by MishalValiyakath** [comment] 2019-10-04 14:48
I am facing the same issue, getting permission denied if we explicitly add the pip3.6 install in the post-deployment script. Also, in my case there is extra index url as well.

**Comment by MishalValiyakath** [comment] 2019-10-08 10:23
Hi @kraigb , please let us know if any update is there on this, this is a show stopper for us to deploy our production workload to azure app service with flask API. Are there any workarounds to get it(Flask API to Azure App Service(Linux)) deployed with all the dependencies meanwhile waiting for the actual fix?

**Comment by MishalValiyakath** [comment] 2019-10-22 09:21
@kraigb, the original issue I opened is now closed with resolution from @Dann1112. It will be great if we can update this information as well in our documentation. 
@HK-Zhang and @jxjia, please check the resolution provided on the linked issue, it fixed mine.

**Comment by kraigb** [comment] 2019-10-22 11:53
Yes, I'll be working on a doc update. I've finally gotten the same solutions through internal conversations.

Here's the solution from the other issue:

There is a parameter that gets added when you create a Python App Service from command line that is not created when you set up an App Service for Python manually.

{
"name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
"value": "True",
"slotSetting": false
}

You'll need to go to App Service -> Configuration -> Application Settings -> New Application Setting and add it there.

Source: Enable/disable build actions (Configurable settings)
https://github.com/projectkudu/kudu/wiki/Configurable-settings#enabledisable-build-actions

**Comment by kraigb** [comment] 2019-10-22 16:24
@HK-Zhang Please close this issue at your convenience, as the solution is in a previous comment.

**Closed** 2019-10-23 00:22 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, support-request

**Comment by retorquere** [comment] 2021-09-29 15:13
I'm still getting errors caused by missing modules that are listed in my requirements.txt. I realized this may not be the correct issue to report this on, but I've been googling for hours, and this is the first hit that seems relevant.

**Comment by CornadaInflictor** [comment] 2021-10-14 23:46
me too

**Comment by varleg** [comment] 2021-12-04 20:00
also got issues with. requirements.txt not being installed during zip deployment. scm_do_build is true
