### ISSUE TITLE
Yaml Snippet example arguments don't match Arguments listed right below it.

### ISSUE THREAD

**Issue by sonofhammer** [MicrosoftDocs/vsts-docs#4922] opened 2019-07-18 19:50 UTC
List of arguments in top YAML snippet that are not  defined in Arguments section
* buildType
* definition
* specificBuildWithTriggering
* buildVersionToDownload
*  branchName
* pipelineId
* artifactName
* itemPattern
* targetPath

List of arguments that are defined, but are not given in the YAML snippet example
* source
* preferTriggeringPipeline
* artifact
* patterns
* path
* pipeline
* runVersion
* runBranch
* runId

Granted, some of those are aliases of one another, but it's hard to tell which are which.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03d67d0-8738-72e6-dbe7-324c1784d4fc
* Version Independent ID: bbb4d774-cd98-3ecb-7ccf-5f49e6f2b425
* Content: [Download Pipeline Artifact task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/download-pipeline-artifact.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismyth**

**Comment by willsmythe** [comment] 2019-07-19 15:43
Thanks for reporting. Adding @chasewilson to look into what happened (since I thought they were in sync). If not, they should be ...

**Comment by MisinformedDNA** [comment] 2019-08-08 21:36
Agreed, the issue here is that many of the arguments have aliases, which leads to inconsistencies. For instance, `specificBuildWithTriggering` is [listed as an alias](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/DownloadPipelineArtifactV2/task.json#L66-L69) for `preferTriggeringPipeline`, but all the samples and YAML generation all seem to use the alias instead of the "name".

**Comment by djee-ms** [comment] 2019-08-29 15:27
Just got caught by this, the argument names in the first YAML snippet (like `buildType`) do **not** work, only the ones listed below in the table (so _e.g._ `source` instead) and the other examples.

**Comment by henry-padilla** [comment] 2019-09-04 13:51
Any ETA on when this is going to get fixed? I need to know what to put where and this documentation isn't helping.

**Comment by chasewilson** [comment] 2019-09-04 16:18
Hi @sonofhammer, @MisinformedDNA, @djee-ms, @henry-padilla, thank you all for the feedback! You are correct and the documentation should reference the aliases and I will be updating shortly. There is some behind the scenes stuff happening today so if it isn't live today, it should be by tomorrow.

**Comment by chasewilson** [comment] 2019-09-04 16:20
@djee-ms, I believe the argument names listed in the snippet should work. do you have any more information in your situation you can share?

**Comment by djee-ms** [comment] 2019-09-04 17:19
@chasewilson > Weirdly enough I am pretty sure that it used to work some weeks/months (?) ago, but reusing that same yaml template again now fails. So possibly a regression with aliases on your side? In any case switching to the ones not in the snippet worked, so I didn't bother more.

**Comment by chasewilson** [comment] 2019-09-04 23:08
@djee-ms Hmm looking at the task here, it doesn't seem like it shouldn't work. I'm glad you have a working pipeline though :) if you do feel like opening and issue with the developer community here, it's always appreciated!

@sonofhammer, @MisinformedDNA, I'm finishing up the corrections now. Thank you for the feedback and please feel free to open a new issue you if you have anything else! I'll be closing this for now.

**Closed by chasewilson** 2019-09-04 23:08 UTC
Labels: Pri2, devops-cicd/tech, devops/prod
