### ISSUE TITLE
Unclear how to combine feature branch CI builds and PR builds

### ISSUE THREAD

**Issue by alarobric** [MicrosoftDocs/vsts-docs#3951] opened 2019-04-12 18:14 UTC
Currently my pipeline is double triggering on any branch with an open PR. I get one build for the commit to the branch, and another for the PR. 
How do I configure this for only one build in this scenario? This is probably a fairly common case that should be mentioned on this page also.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by Izzmo** [comment] 2019-04-24 13:57
You probably need branch filters with a naming strategy. How I've done this in the past is use a single build pipeline for the project and then use naming to your advantage for triggers.

- master branch - trigger whenever that is updated
- feature/ or bug/ - will trigger based on that and potentially flow to a PR environment for review (Pull request release)
- refs/pulls - This is default and will trigger based on a PR

**Comment by steved0x** [comment] 2019-07-03 19:41
@alarobric I apologize for the great delay in responding to this issue. Were you able to get it resolved? If so, what did you change, and if it is something I can add to the docs to make it clearer, I will do so.

If you are still getting the double builds, can you share your triggers, whether it is a classic editor or YAML pipeline, and the repo type (GitHub, Azure Repos Git, etc..)

The strategy given by @izzmo might work for you, but if your CI trigger branch filters and PR trigger branch filters overlap, I think you will get two builds. Let me check on that a little more to see if that is expected behavior.

**Comment by alarobric** [comment] 2019-07-05 03:57
Well I realised that actually this is creating two different builds. The CI trigger on the feature branch is building that branch, while the PR trigger (based on the build validation branch policy) is building the result of the theoretical merge of that branch into master.

It's still not ideal for us to have both, but I can see reasons why you might want that. And I can't think of a way to trigger the CI feature branch builds whenever a pull request does not exist, but not once a PR is opened...

**Comment by Izzmo** [comment] 2019-07-09 11:59
@alarobric is the policy that the feature branch can only be updated via PR?

If not, then you'll have to stick with two builds as the system won't be able to differentiate a commit that's done on the branch with a PR and one that is not since they live in two different contexts.

If you enforce a policy where the feature branch, treated like a master, is only updated via a PR, then you could enforce it and only have a single build.

**Comment by FISHMANPET** [comment] 2019-12-27 18:02
I've got a project with a fairly simple workflow using both CI and PR validation, to control Azure Automation Runbooks, driven with a Github repo.  When commits are made to master, the changes are published to the production Automation account.  PRs are required to merge into master, and the PR rules require the branch to be up to date with Master before they can be merged.  When a PR build is triggered, the changes are published to a test automation account.  You can also trigger a a deploy of your changes to this test environment with a commit comment that my pipeline reads.

Anyway I point all that out to show how simple my workflow is, so what I'm looking at may not work for more complicated work flow, but I think it will work for mine.  I also haven't tried to implement this yet, but it should be possible.  Using `git ls-remote origin 'pull/*/head'` from within a repo in detached head state (basically the same state it's in during a pipeline) I'll get all PRs for my repo, because Github makes special branches for them, along with the commit hash of that PR.  Since a CI build knows the hash of the commit it's running against, I was thinking of adding a step that grabs my hash, and compares it to all the PR hashes, and if there's a match, cancel the build.

As I write it out, also not sure how that would work out if for example multiple CI builds for the same branch were triggered, maybe depending on timing it would run one but not the other, but running one is better than running both.

Another option would require using the Github API.  Since the pipeline knows the branch _name_ it could query github and see if there are any open PRs for that branch and if so cancel the build.  That's an option that could potentially be implemented within the tool itself, add an option to disable CI builds when a PR build is triggered for the same branch, and whenever github triggers the CI build, the first thing ADO could do is query Github to see if there's an Open PR before triggering the CI build.

**Comment by Izzmo** [comment] 2019-12-27 22:06
@FISHMANPET I don't think this is related to GitHub at all. While, in theory, you could apply the same thing with webhooks in ADO, it would be hard to do.

@alarobric can we close this?

**Comment by FISHMANPET** [comment] 2019-12-27 22:14
Not sure what you mean by not related to GitHub.  The root of if is that when you configure CI and PR builds, two webhooks are created in the GitHub repo, one to notify on all branch changes, one to notify on all pull request changes.  Pushing to a branch with an open pull request triggers both webhooks, which is why two builds get triggered.  I'm suggesting a way, either inside the build pipeline, or in the same place as the logic that determines what to build based on branch, that would, if enabled, check on every CI build to see if there is an open PR for the branch that triggered, and not execute the CI build if there is an open PR.

If this was a setting in the trigger, then the user would have the option of enabling it.  Depending on their setup they may want two builds to trigger when pushing to a branch with an open PR, in which case they wouldn't enable this setting.  But if they don't want two builds to trigger on a PR they could enable this setting.

**Comment by steved0x** [comment] 2020-02-19 15:01
This is a great discussion, I am going to close this issue since the initial question is resolved (thank you contributors to the thread) but please feel free to continue the discussion over at https://developercommunity.visualstudio.com/spaces/21/index.html since ti sounds like some of the ideas here would be a good addition to the product. Thank you.

**Closed by steved0x** 2020-02-19 15:01 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
