### ISSUE TITLE
Where is Yarn preinstalled?

### ISSUE THREAD

**Issue by wojtekmaj** [MicrosoftDocs/vsts-docs#1881] opened 2018-09-26 10:12 UTC
On Languages -&gt; JavaScript page it is told that "Yarn is available preinstalled on some Microsoft-hosted agents". I can't seem to find the exact info on which. I'm getting an error:

```2018-09-26T10:10:33.5393824Z /home/vsts/work/_temp/cc3fb5e1-f408-4795-9aa6-093141ecb79d.sh: line 1: yarn: command not found```

on Ubuntu Microsoft-hosted agent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=vsts&tabs=web)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment] 2018-09-26 13:01
Possibly a bug. Ubuntu 16.04 has Yarn 1.9.4 preinstalled. I will investigate.

**Comment by vtbassmatt** [comment] 2018-09-26 13:07
I can't repro this. My build uses the Hosted Ubuntu image and simply runs a script:

```bash
which yarn
yarn init
```

I get:

```
2018-09-26T13:06:02.5493253Z Generating script.
2018-09-26T13:06:02.5690045Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/86bd857b-8044-4477-92f4-0ccc24b5fbda.sh
2018-09-26T13:06:02.5792405Z /usr/bin/yarn
2018-09-26T13:06:08.6005724Z yarn init v1.9.4
2018-09-26T13:06:08.7155160Z error An unexpected error occurred: "Can't answer a question unless a user TTY".
```

(Although there's an error, it's obviously coming from Yarn, proving that Yarn is installed.)

**Comment by wojtekmaj** [comment] 2018-09-26 13:19
Here's my attempt of CI configuration: 

https://github.com/wojtekmaj/nightmare-wait-for-url/pull/1

Could you hint me on what am I doing wrong?

**Comment by vtbassmatt** [comment] 2018-09-26 15:13
Hmm, that looks right to me. Humor me and try one debugging step: can you remove the NodeTool installer step and then see if the `yarn install` step still fails? (I'm kind of flying blind here - I can't imagine why that would break anything, but it's also the only thing that happens in the build before `yarn`.)

**Comment by vtbassmatt** [comment] 2018-09-26 18:10
Not sure :(  @dakale can you think of anything that might be going wrong with the Ubuntu image?

**Comment by dakale** [comment] 2018-09-26 21:30
I cant reproduce this either. The only difference I can see, when I export to yaml  is:
```yaml
steps:
- script: 'yarn install' 
  displayName: 'Command Line Script'
```
vs
```yaml
steps:
- script: yarn install
  displayName: 'Install dependencies
```

Notice the script in my example is single-quoted. Did you write this manually or export it from the web ui? It may be worth trying to wrap the command in quotes like the first example, but Ill continue to investigate the root cause, (or figure out why quotes are required)

**Comment by vtbassmatt** [comment] 2018-09-26 22:36
The quotes *should* get eliminated during parsing but I'm likewise curious about what actually happens.

**Comment by wojtekmaj** [comment] 2018-09-27 06:46
I added a script from one of Yarn maintainers to install Yarn but that didn't help either. This is really odd, have a look at those logs:

https://dev.azure.com/wojtekmaj/wojtekmaj/_build/results?buildId=19&view=logs

The only thing I'm curious about is this in "Install Yarn" step:

```sh
2018-09-27T06:43:51.4101738Z > If this isn't the profile of your current shell then please add the following to your correct profile:
2018-09-27T06:43:51.4121917Z    
2018-09-27T06:43:51.4137012Z export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
```

So, perhaps PATH is missing? Because *clearly* Yarn is installed now.

**Comment by wojtekmaj** [comment] 2018-09-27 07:03
FYI, setting `vmImage` to `win1803` makes it running like a charm. You know, I think I'm a Windows guy after all... ;)

**Comment by vtbassmatt** [comment] 2018-09-27 11:33
`export`ing PATH won't work because each step runs in a new process. Variables you set in one step don't live to the next step unless you add the right incantation: `echo "##vso[task.setVariable variable=MY_VAR]my_value"`. And I see that the Yarn installer edited .bash_profile to try and make it sticky, but we invoke bash with `bin/bash --noprofile --norc`.

That aside, I'm stumped! I even tried building your repo at the last commit where you pointed to Ubuntu (be935e1a6f65a10c91cf22929bb5a9850b1625a2), and... [it worked](https://dev.azure.com/mattc-demo/Test1/_build/results?buildId=463&_a=summary&view=logs)! I got a newer agent than you (140 vs 136) and ran with full debugging turned on.

It looks like we have a bug here, and not with the docs. I'm going to close this issue, but would you reach out to me at mattc at xbox.com? I'd like to get to the bottom of it with you.

**Closed by vtbassmatt** 2018-09-27 11:33 UTC

**Comment by wojtekmaj** [comment] 2018-09-28 09:04
Oh man!
I changed
```
  vmImage: 'Ubuntu 16.04'
```

(what was automatically created when I was setting up things directly from GitHub) into:

```
  vmImage: 'ubuntu-16.04'
```

and it worked like a charm!

**Comment by vtbassmatt** [comment] 2018-09-28 11:11
Very weird... there are literally two `case` statements that fall through to the same output, one with the hyphen and the other without. We'll keep an eye out for this behavior, though.
