### ISSUE TITLE
URL format changed ?

### ISSUE THREAD

**Issue by vmaruhpe** [MicrosoftDocs/vsts-docs#3204] opened 2019-02-01 04:32 UTC
Until very recently automation using the format https://dev.azure.com/{your organization}/{your project} to clone a repo from Azure DevOps worked well. This seems to be broken now as the format changed to  https://project@dev.azure.com/_git/organization essentially breaking the pattern of using https://username:password@dev.azure.com/{your organization}/{your project} . While using this pattern is not ideal, the change is breaking existing automation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 419f53ee-528e-bb71-31b2-e67ddef00ddd
* Version Independent ID: f648e732-f5fe-360d-d185-8278c1af144e
* Content: [Visual Studio Team Services is now Azure DevOps Services - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/what-happened-vsts?view=azure-devops)
* Content Source: [docs/user-guide/what-happened-vsts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/what-happened-vsts.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by steved0x** [comment] 2019-02-04 18:31
@vmaruhpe I have forwarded this to the team, I am closing this issue as a duplicate of https://github.com/MicrosoftDocs/vsts-docs/issues/3204 and we'll update that one with any new info. Sorry for the trouble and thanks for letting us know.

**Closed by steved0x** 2019-02-04 18:31 UTC
Labels: devops/prod, user-guide

**Comment by vmaruhpe** [comment] 2019-02-04 23:08
thank you @steved0x

**Comment by chcomley** [comment] 2019-02-06 17:18
@vmaruhpe We are sorry for the trouble. Could you please provide an email address so we can contact you directly? Thanks very much.
