### ISSUE TITLE
Example content for testAssemblyVer2 needs to express newlines

### ISSUE THREAD

**Issue by jimmylewis** [MicrosoftDocs/vsts-docs#1580] opened 2018-08-21 22:04 UTC
There needs to be newlines to separate the match expressions.  This could be done with double quote and escape characters, e.g: 
`"**\\*test*.dll\n!**\\*TestAdapter.dll\n!**\\obj\\**"`

or by making use of multiline operators in YAML, e.g.:

```
#testAssemblyVer2: |
#   **\*test*.dll
#   !**\*TestAdapter.dll
#   !**\obj\**
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bd8dd1-7650-8c18-2553-38a8bc54e892
* Version Independent ID: f9fa517a-7adc-e327-d12e-256295a1ed52
* Content: [Visual Studio Test](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/test/vstest?view=vsts)
* Content Source: [docs/pipelines/tasks/test/vstest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/vstest.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by jimmylewis** [comment] 2019-03-01 07:04
bumping this to give it a little more lifetime, as the existing example does not work - users who copy it will have to debug the syntax issues.

**Comment by tillig** [comment] 2019-03-27 16:08
This just ate my lunch for a couple of hours. 😠 Getting the docs correct and using _double quotes_ in the example to ensure `\n` gets properly interpreted is pretty important to getting people on the path to success, especially when most of the editing is done in YAML instead of through a nice visual designer that handles the serialization.

It wouldn't hurt to get some YAML multiline examples [on the pattern matching page, too](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=azure-devops&viewFallbackFrom=vsts) since none of the ones there would actually work if you pasted them into a pipeline YAML doc.

I'm still fighting through trying to get multiple exclusions (`!pattern`) working, starting to think it's related to #2551. Anyway, having a working example would be great.

**Comment by TroySchmidt** [comment] 2019-05-09 15:31
Definitely need to fix this.  Even using the new online YAML graphical editing puts in invalid values for `testAssemblyVer2` and *ONLY* by seeing this thread was I able to use the pipe multi line and fix it.

**Comment by prawalagarwal** [comment] 2019-05-15 07:46
@andyjlewis Can we push the changes as raised by @jimmylewis or @dlumpp above?

**Comment by olivermue** [comment] 2019-05-16 12:50
Just ran into the same situation and asked [on SO](https://stackoverflow.com/q/56166045/1838048) and got the same answer as @jimmylewis already posted in his initial post of this issue. And I can confirm that this approach works. Also I posted the issue on [Developer Community].(https://developercommunity.visualstudio.com/content/problem/570805/working-with-multiple-pattern-matchings-in-vstest.html).

**Comment by andyjlewis** [comment] 2019-05-21 12:21
Following up with the product team.

**Comment by steved0x** [comment] 2019-05-23 13:40
@jimmylewis We just checked in a doc fix for this and it should be live soon. Thank you for letting us know.

**Closed** 2019-05-23 22:43 UTC
Labels: area - pipelines, devops/prod, doc-bug

**Comment by bing-ranplan** [comment] 2020-07-22 17:06
Hit the same problem and took me a couple of hours before seeing this thread.
In my situation, I have to write a script to dedup the list of test files since the test projects could be referencing each other and the same test assemblies appear in multiple output directories. (We know it's bad but we've not got around to sort them out yet).
Then I had this issue when I got the list of specific files and echo that as a variable to be used for vstest task's testAssemblyVer2. The example needs improving.
