### ISSUE TITLE
[error]Solution not found using search pattern 'd:\a\1\s\**\*.sln' when using the above example

### ISSUE THREAD

**Issue by nadvolod** [MicrosoftDocs/vsts-docs#6359] opened 2019-11-13 20:39 UTC
Hello, I went through the steps to setup an initial pipeline. After saving the .yml file as specified, I'm getting the following error on the VSBuild step:
[error]Solution not found using search pattern 'd:\a\1\s\**\*.sln'.
Here's also a screenshot: https://screencast.com/t/m2SucrY7pPNW
Here's the repo just in case: https://github.com/nadvolod/pipelines-dotnet-core

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec716c61-248c-75c9-2bc7-262749cc7421
* Version Independent ID: 45f47edc-e800-2c42-416a-92cd93c9e892
* Content: [Build, test, and deploy .NET Core apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops#feedback)
* Content Source: [docs/pipelines/ecosystems/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/dotnet-core.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment] 2019-11-14 05:22
@nadvolod  Thank you for the feedback.

Please see if [this post](https://stackoverflow.com/questions/56634927/solution-not-found-using-search-pattern-d-a-1-s-sln) resolves the issue.

If not, please use either the [support bot](https://azuredevopsvirtualagent.azurewebsites.net/) or reach out to the product team at [Azure DevOps community](https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

**Comment by nadvolod** [comment] 2019-11-14 14:42
@msebolt thanks for the resource. Yes, maybe it would fix it. But shouldn't the example in the docs work out of the box is my point? If I forked a .NET repo and followed the example, it should work flawlessly, right?

**Comment by msebolt** [comment] 2019-11-14 23:46
@nadvolod  You're correct, we just need the issue confirmed before updating any documentation.  Usually the product team handles product feedback or support requests.

**Comment by nadvolod** [comment] 2019-11-15 14:40
@msebolt so the confirmation, is that something you all will do? Or you expect that of me?

**Comment by msebolt** [comment] 2019-11-18 18:10
@nadvolod I'll assign this to the author to see if they experience the same issues.

**Comment by juliakm** [comment] 2020-01-09 19:40
Confirming that I run into the same issue when running the ASP.Net Core (.Net Framework) template. The problem is that there is not a .sln file in the example repository. Running the ASP.NET Core template does work.

**Comment by juliakm** [comment] 2020-01-10 16:16
I've added a pull request to the example repo - https://github.com/MicrosoftDocs/pipelines-dotnet-core/pull/53.

**Comment by vtbassmatt** [comment] 2020-01-10 17:43
I think this should be fixed in the product, not by altering the sample. The sample represents a real-world-ish example. I've opened a bug to track this in Azure DevOps and will close this doc bug.

**Closed by vtbassmatt** 2020-01-10 17:43 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
