### ISSUE TITLE
Please make clear whether caching is out of preview

### ISSUE THREAD

**Issue by iain-peddie-tessella** [MicrosoftDocs/vsts-docs#7000] opened 2020-01-20 15:08 UTC
The text of this page makes it seem that this functionality is out of preview - no mention of pipeline caching being in preview is made. However, the title of this page in the tree view menu on the left hand pane is `Reduce build time using caching (Preview)`. Either this is an oversight, or this page doesn't make clear that this feature is still in preview.

I'd expect the content of the page, and any text in hyperlinks opening it to be consistent about whether this is a feature in preview or not. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops#feedback)
* Content Source: [docs/pipelines/caching/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/caching/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment] 2020-01-21 17:55
@iain-peddie-tessella Thank you for the feedback.

There are often release date discrepancies between **Azure DevOps services** and **Azure DevOps server** features, please refer to the [Azure DevOps timeline](https://docs.microsoft.com/azure/devops/release-notes/features-timeline) for information.

Assigning this to the author for further review.

**Comment by FrancescElies** [comment] 2020-02-07 07:20
Any news on this?

**Comment by Slooz** [comment] 2020-04-05 19:53
Duplicate of #6300

**Comment by steved0x** [comment] 2020-04-06 14:52
It is out of preview and I am fixing that TOC right now, sorry for the delay.

**Closed** 2020-04-06 15:48 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
