### ISSUE TITLE
No documentation on Containerized Build Agents

### ISSUE THREAD

**Issue by craigjar** [MicrosoftDocs/vsts-docs#3279] opened 2019-02-07 15:52 UTC
Document does not cover an alternate method of deploying an agent which Microsoft provides, which is via Docker Container.  https://github.com/Microsoft/vsts-agent-docker

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23328b13-f079-ad21-5d7a-6c640f25391c
* Version Independent ID: 4a39889d-fa00-ae2b-aa43-f358631b7b1a
* Content: [Deploy a build and release agent on Linux - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/agents/v2-linux?view=azure-devops)
* Content Source: [docs/pipelines/agents/v2-linux.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-linux.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment] 2019-03-15 14:16
This is in progress. I need to get it moved into the docs repo once it's ready.

**Comment by vtbassmatt** [comment] 2019-04-02 13:31
Dupe of #1494

**Closed by vtbassmatt** 2019-04-02 13:31 UTC
Labels: pipelines
