### ISSUE TITLE
Please clarify permissions and roles

### ISSUE THREAD

**Issue by djpugh** [MicrosoftDocs/vsts-docs#6809] opened 2020-01-02 16:34 UTC
I'm currently (as a Project administrator) unable to change permissions on the project's environments - 
"needs the following permission(s) on the resource Environments/... to perform this action: Administer Permissions"

Where these permissions are defined, and what roles correspond to what are not explained in this documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Environment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops#security)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/environments.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by djpugh** [comment] 2020-01-02 16:40
This could be a DevOps issue so have opened at https://developercommunity.visualstudio.com/content/problem/872257/environments-permissions-changing-not-possible-as.html

**Comment by msebolt** [comment] 2020-01-06 20:20
@djpugh Thank you for the feedback and for soliciting feedback from the DevOps product team.

Assigning this to the author for review.

**Comment by RoopeshNair** [comment] 2020-01-30 10:19
Raised [#PR877](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/877) clarifying the user permissions for environments

**Closed** 2020-01-30 10:25 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement

**Comment by spottedmahn** [comment] 2021-05-26 03:00
Hey @RoopeshNair - "#PR877" is a dead link, any chance you got a new one?  I too am trying to understand this error... thanks!

**Comment by jikuja** [comment] 2022-10-10 12:41
PSA for others coming from Google: related issue on ADO feedback site: https://developercommunity.visualstudio.com/t/environments-permissions-changing-not-possible-as/872257

`This behaviour is by design today. One need to have account level owner permission to provide manage permissions on environments. This is at par with how the deployment group scenario is supported.` (SIC)

Looks like service imitation.
