### ISSUE TITLE
Installed task not updating itself after I've published an update to the extension.  

### ISSUE THREAD

**Issue by ClydeDz** [MicrosoftDocs/vsts-docs#4087] opened 2019-04-29 07:00 UTC
Hi,

I followed [this guide](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops#preparation-and-required-setup-for-this-tutorial) and was successfully able to publish an extension. However, I have a question around the installed task updating itself after I've published an update to the extension.   

## Elaboration
Please follow along:
1. **Version 0.1.0**
I published version 0.1.0 to the marketplace (**visibility: private**) and shared it with my organisation to test it out. Let's assume the description for this task at this version was `placeholder description`.

1. **Version 0.2.0**
Few hours later, I published version 0.2.0 (**visibility: private**). Let's assume the description has been updated to`actual description`.  The manage extension pages tells me its already shared with my organisation. 
However, in a new build pipeline:
     * when I add the task, the description still says `placeholder description`
     * when queue a new build the header still shows Version 0.1.0.

## Question   
1. Doesn't the task get automatically updated, [as per the docs](https://docs.microsoft.com/en-us/azure/devops/extend/publish/integration?view=azure-devops#update-an-item) and [this detailed explanation of how it works in the background](https://github.com/MicrosoftDocs/vsts-docs/issues/3800#issuecomment-479166606)? 
1. If not, would I need to uninstall and reinstall the extension for version 0.2.0 to take effect?

I read about [bundling multiple versions](https://docs.microsoft.com/en-us/azure/devops/extend/develop/integrate-build-task?view=azure-devops#traditional-extension-layout) but I'm really after pushing minor updates / bug fixes to the current major version and was hoping it would auto-update it for the organisations that have installed. 

Hope this makes sense? Looking forward.

Thanks,
@ClydeDz 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a Build or Release Task](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-build-task.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment] 2019-05-22 20:01
Hi @ClydeDz, Please accept my apology for our delayed response. We're glad you were able to successfully publish your extension! I've assigned this issue to a PM and writer, so one of them should be in touch soon with an answer to your question. Hope you're having a great day.

**Comment by Farzad-Jalali** [comment] 2019-06-06 14:25
> Hi @ClydeDz, Please accept my apology for our delayed response. We're glad you were able to successfully publish your extension! I've assigned this issue to a PM and writer, so one of them should be in touch soon with an answer to your question. Hope you're having a great day.

I got the same problem, could you please kindly, provide the solution publicly.
many thanks

**Comment by isamauny** [comment] 2019-07-04 10:55
Hi , is this actually a bug ?  I faced the same issue as well. Had to de-install and re-install the extension from the marketplace for the new version to be taken in account in my pipeline. Thanks.

**Comment by brianfleibenzon** [comment] 2019-07-30 14:02
Hi, I am facing the same issue. I can see in the Organization Settings that the extension has been updated, but when I try to use it in the pipeline, I cannot find the way to use the new version.

Thanks

**Comment by tsteenbakkers** [comment] 2019-07-31 08:54
We are also facing this issue. Adding / removing tasks from an extension does seem to be reflected when publishing the extension (provided the extension version was also upped). besides the fields description (which OP wrote about) also name and friendlyname field changes and adding / removing task inputs appear not to be reflected when updating them and publishing them as part of an extension.

i Initially thought this to be a caching issue on my local browser, but even clearing the cache or asking another user to check the task seem to give the same result.

**Comment by brianfleibenzon** [comment] 2019-08-01 12:36
Hi, I was able to fix the issue updating the task version in task.json file before creating a new extension version. 

When you run the command `tfx extension create --manifest-globs vss-extension.json --rev-version` it just updates the version number in the vss-extension.json file, but it doesn't change it in the task.json. So what I did is first update the task.json version with the new one and then run the command.

I hope this helps you too.

**Comment by chcomley** [comment] 2019-08-01 18:30
Thank you for the update, @ClydeDz, and for sharing your fix. I'll follow up with the PM to determine an update to the article. I hope this works for others, as well. If you do have further issues, please contact [Support](https://visualstudio.microsoft.com/vs/support/#talktous). Thank you!

**Comment by chcomley** [comment] 2019-09-03 17:17
Hi @jordynniara, I'm sorry it didn't work for you. Please [contact Support](https://visualstudio.microsoft.com/vs/support/#talktous). Thanks and best of luck to you.

**Comment by eric-labelle** [comment] 2019-09-19 20:31
Why is this issue closed? @ClydeDz never actually gave a solution like @chcomley is saying. The only thing was what I consider a workaround provided by @brianfleibenzon (_which works_) although it's a pain to always bump this task.json patch version manually in order to see our changes to the task reflected when developing a task. I'm not saying it should update automatically when the task is actually public, but when it's private and under-development it's time consuming to iterate quickly on the task.

It is really confusing that the Azure Extension portal in my organisation is actually showing that the extension was updated, but pipeline using the task are stuck to previous version until the task.json version is changed OR I uninstall and reinstall the task everytime.

**Comment by chcomley** [comment] 2019-09-19 20:48
Hello all, I suppose I figured the workaround sufficed when it was closed back in August, not sure. I've reopened this issue and have an engineer looking into it as we "speak." Thanks for speaking up, @eric-labelle. @jordynniara, curious whether you contacted Support and what may have come from it?

**Comment by edglas1** [comment] 2019-09-20 12:37
Thanks @brianfleibenzon for posting the solution that you need to update the version number in task.json as well on the tfx command line. Clearly having to specify the version in two places is confusing and should not be necessary. I will check to see why we have this requirement.

**Comment by chcomley** [comment] 2019-09-26 13:12
Following up on this - @ClydeDz, are you interested in @edglas1's findings? Please do let us know. @edglas1, how do you believe we could clarify this within the article? Thanks.

**Comment by andreasschild** [comment] 2019-09-26 20:32
The command `tfx extension create --manifest-globs vss-extension.json --rev-version` is updating the patch version of the AzDo extension, but not the patch version of the custom task (task.json). I think, that the new version of the custom task is not fetch by the AzDO organization, because it doesn't find a new version (by design).
I have a simple script, which sets the patch version to the build number. With that, I make sure, that the version of the task.json changes after each code change.
@eric-labelle: I am avoiding the waiting time by having a dev custom task which I am uploady directly into AzDO organization by using the tfx command `tfx build tasks upload --overwrite --task-path "myPathToTheTask" --service-url "https://myOrg.visualstudio.com/DefaultCollection" --auth-type pat -t "xxx"`. And this is even faster if you are deleting the task before (be careful. This deletes versioning). Then you can directly run integration tests. If everything is fine, I am deploying the task to the publisher.

**Comment by chcomley** [comment] 2019-10-08 18:57
@andreasschild Can you please let us know the status of this? Has this issue been properly taken care of? Thanks!

**Closed** 2019-10-15 20:09 UTC
Labels: Pri1, devops-ecosystem/tech, devops/prod, doc-bug, extensibility, product-question

**Comment by eric-labelle** [comment] 2019-10-23 12:20
**Thank you** @andreasschild for this command, first time I've heard of it. 

It would worth mentioning on [the guide](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops#optional-install-and-test-your-extension) as it is **A LOT** more convenient to develop and test new tasks or next task iteration using another GUID to keep the first version untouched. 

Make sure to mention in the guide the pat requires only "Agent Pool" permission as it is probably one of the last I guessed while trying this command. Or simply link to https://github.com/microsoft/tfs-cli/blob/master/docs/buildtasks.md. I wish I had seen this months ago!

**Comment by ngarg-panw** [comment] 2020-12-10 23:00
Hi, 
I am also facing the same issue. For me, i had already updated the task versions as well to match with extension version, but still the users have to uninstall and install the new version.
Also, if they have existing pipelines, they will have to again add the tasks because now they have changed from @1 to @2. Should these things not happen automatically?

**Comment by pastinepolenta** [comment] 2022-07-06 12:15
Sorry for posting on a closed issue, if you prefer I can open a duplicate.
But this issue is closed without a resolution. Even if my task.json the patch version is updated (as well as the vss-extension.json) and in my organization the update is taken into account, in my pipeline the new patch version is not fetched (the pipeline stays 3 patch versions behind).

It feels like a bug, since in the pipeline we can only specify the major version of a task.

**Comment by WilliamAntonRohm** [comment] 2022-07-06 23:18
@pastinepolenta -- Mirko, thank you for your follow-up.  This repo is solely for documentation issues, and this seems product-related. To make sure it gets in front of the right people, [please add it here](https://developercommunity.visualstudio.com/search?space=21).

**Comment by christopherbadman** [comment] 2022-11-11 16:42
For anybody else running into issues related to this, I also observed this behavior, but it was due to some unlikely circumstances - but perhaps you have the same.

I was publishing my extension using the `PublishAzureDevOpsExtension@3` task in a YAML pipeline. This task was configured with `updateTasksVersion: true` (which seems also to be the default if this input is omitted).

What this does is forces all tasks to have the version declared in the _extension_ manifest.

In my case, the task currently deployed on the server (1.2.x) had a higher version than the extension (1.1.x). I was attempting to upgrade the task by setting the version in the _task_ manifest to 1.3.x, but the `updateTasksVersion: true` was overwriting this back down to 1.1.x, so presumably Azure DevOps was ignoring any upgrade of this task, because it looked to be an older version than what was already deployed.

**Comment by MBerdasco** [comment] 2023-08-04 07:47
If you are using a self-hosted agent, best workaround I´ve found for this issue is: Go to the agent´s _work\_tasks folder and delete the folder which contains the task (usually, it will start with the name of the task + GUID). Next time you launch the pipeline which is using the task, it will not find a cached one and will be enforced to download the updated one.
