### ISSUE TITLE
Compile into container and extract artifacts

### ISSUE THREAD

**Issue by simardst** [MicrosoftDocs/vsts-docs#6522] opened 2019-11-29 15:33 UTC
Is there a way to compile into a container (docker) and extract the build artifacts?  I'm lokking for a recipe that would work with 
Azure DevOps Microsoft-hosted agents.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment] 2019-12-02 22:22
Duplicate of #6521

**Closed by WilliamAntonRohm** 2019-12-02 22:22 UTC
Labels: Pri1, cba, devops-cicd/tech, devops/prod, duplicate
