### ISSUE TITLE
Add the possibility to include/exclude pipelines names for schedules

### ISSUE THREAD

**Issue by agneszitte-nventive** [MicrosoftDocs/vsts-docs#6055] opened 2019-10-18 15:07 UTC
At the moment, if I'm adding a scheduled trigger in my yaml file, I don't have the possibility to include/exclude pipelines names.
For example, I'm adding this schedule and use the same yaml for multiple pipelines but I want to exclude one specific pipeline to use this schedule.

```
schedules:
- cron: "30 09 * * Mon-Fri"
  displayName: 'Nightly weekdays build - 4:30 EST'
  always: false
  branches:
    include:
    - master
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment] 2019-10-18 21:28
@agneszitte-nventive  Thank you for the feedback and for starting dialogue with the product team.

This may not be feasible since by design each build can include multiple schedules/triggers which can then include multiple repos/branches.

However, for now just create a new branch with an additional YAML schedule and we'll see how the product team responds.

**Comment by msebolt** [comment] 2019-10-18 21:50
@agneszitte-nventive Apologies, I just realized the issue you created is with other document team.

Please consider moving the issue under **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) where the product team can assess.

**Comment by agneszitte-nventive** [comment] 2019-10-21 15:49
Thanks @msebolt, I entered the issue under "Suggest a feature".
https://developercommunity.visualstudio.com/idea/786778/yaml-add-the-possibility-to-includeexclude-pipelin.html

**Comment by msebolt** [comment] 2019-10-22 19:23
Great, thank you @agneszitte-nventive.  I'm closing the issue now.

Please use the link above for further comments and/or status updates.

**Closed by msebolt** 2019-10-22 19:23 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, product-feedback
