### ISSUE TITLE
What is the meaning of cache

### ISSUE THREAD

**Issue by rnarayana** [MicrosoftDocs/vsts-docs#6690] opened 2019-12-16 18:07 UTC
I think I may have misunderstood the idea of caching here. This page says "the cache step will report a cache hit and the contents of the cache will be downloaded and restored." If it is going to be downloaded again, what is the point of cache? I have a self hosted agent, and this seems to be the exact behavior. All that is happening is, instead of downloading from nuget.org, I am downloading from https://*.vsblob.visualstudio.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops)
* Content Source: [docs/pipelines/caching/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/caching/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment] 2019-12-17 17:11
@rnarayana Thank you for the feedback.

This is not the intended behavior of cache and should be reported to the product team.

Please move the issue [here](https://developercommunity.visualstudio.com/spaces/21/index.html).

@chasewilson

**Comment by msebolt** [comment] 2019-12-20 16:24
Closing this now, please comment below if there are further issues.

**Closed by msebolt** 2019-12-20 16:24 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, product-feedback

**Comment by rnarayana** [comment] 2019-12-20 16:35
> @rnarayana Thank you for the feedback.
> 
> This is not the intended behavior of cache and should be reported to the product team.
> 
> Please move the issue [here](https://developercommunity.visualstudio.com/spaces/21/index.html).
> 
> @chasewilson

Hey, thanks for your response. Am i supposed to report the issue elsewhere or have you taken care of it already?

**Comment by msebolt** [comment] 2019-12-20 16:46
@rnarayana Thank you for the update, issue created at https://developercommunity.visualstudio.com/content/problem/864520/issues-with-cache-behavior.html.
