### ISSUE TITLE
TFSMigrator reports that it can't find my .dacpac file.

### ISSUE THREAD

**Issue by git-gone** [MicrosoftDocs/vsts-docs#410] opened 2018-03-27 09:17 UTC
I have an *import.json* file that contains the Source Property;  I was intending to do a Dry Run.
  "Source": {
    "Location": "https://noiwonttellyoumykey",
    "Files": {
      "Dacpac": "Tfs_DefaultCollection.dacpac"
    }
-----------------
The ensuing error is
Microsoft Team Foundation Server (R) Tfs Migrator Tool version 16.123.27421.1
Copyright (C) Microsoft Corporation. All rights reserved.

-------------------------------------
  Validating Import File
-------------------------------------

Validating import specification file...

Validation completed with an error.
.\TfsMigrator.exe : + [Error] VS403245: Unable to access Source File Dacpac: Tfs_DefaultCollection.dacpac. Check if it exists.
At line:1 char:1
+ .\TfsMigrator.exe Import /importFile:import.json /validateOnly
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (+ [Error] VS403...k if it exists.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
---------------------------------.
The funny thing is - the file is actually present on the current directory of the process from which tfsmigrator was run.  Am I supposed to upload the .DACPAC  manually to my Storage? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1798e45e-200d-f201-e4dd-58aac2427d29
* Version Independent ID: 86df23f9-1e19-65ae-de6d-cc6069521f34
* Content: [Troubleshooting the migration import from TFS to Visual Studio Team Services (VSTS)](https://docs.microsoft.com/en-us/vsts/articles/migration-troubleshooting?view=vsts#feedback)
* Content Source: [docs/articles/migration-troubleshooting.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/articles/migration-troubleshooting.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **douge**

**Comment by steved0x** [comment] 2018-05-01 18:01
@git-gone I'm sorry for the long delay in responding to this issue, were you able to get it resolved? Do we need to update the documentation to show how to resolve/avoid this issue? Thank you and sorry again for the delay.

**Comment by steved0x** [comment] 2018-05-14 14:11
@git-gone I'm closing this issue - please reopen a new one if the issue is not resolved. Thank you.

**Closed by steved0x** 2018-05-14 14:11 UTC

**Comment by hassanraha** [comment] 2019-03-21 11:43
Hi, I am also facing the same issue.
+ [Error] VS403245: Unable to access Source File Dacpac: \Tfs_DefaultCollection.dacpac. Check if it exists.
Even though the file is in the same directory of import.json

**Comment by aarotech** [comment] 2021-06-01 21:37
I am also having the same issue. There doesn't appear to be any fix and our organization is blocked from the migration process indefinitely if this remains unresolved.

**Comment by dannoe** [comment] 2021-08-10 16:30
@aarotech You have to manually upload the file to the storage container. The import command of the migrator.exe does not execute this step.
