### ISSUE TITLE
Combos.IComboOptions documentation

### ISSUE THREAD

**Issue by danielstefanescu** [MicrosoftDocs/vsts-docs#1229] opened 2018-07-06 09:38 UTC
Where is the Combos.IComboOptions documentation?
The combo control does support a source with value and text e.g. &lt;option value="1"&gt;a&lt;/option&gt;?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97777da6-f32b-a0f2-733f-91304a3ef163
* Version Independent ID: 70bf2041-914b-3f7a-3c05-f026b9c91b5f
* Content: [Combo Control](https://docs.microsoft.com/en-us/vsts/extend/reference/client/controls/combo?view=vsts)
* Content Source: [docs/extend/reference/client/controls/combo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/client/controls/combo.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment] 2018-07-12 18:36
Hi @danielstefanescu , I've forwarded this to the product team, I'll reach back out when they respond :)

**Comment by mongeon** [comment] 2018-08-29 18:03
Any feedback on this issue? I want to bind a Release Definitions array to a combo box and display the name property.

Thanks

**Comment by froens** [comment] 2018-09-18 12:14
I have the same issue. How do we bind to actual objects? A list of strings is not enough for real scenarios, where you want the list to output a value - not the label.

**Comment by pabrams** [comment] 2019-06-18 13:50
Here's your further activity.  Please fix your documents!

**Comment by thomps23** [comment] 2019-06-18 17:35
@chcomley Would you be able to follow up with the product team here?

**Comment by chcomley** [comment] 2019-06-18 18:08
Yes, @thomps23, I've initiated the conversation. I'll report back as soon as possible. Thanks!

**Comment by serkan-inci** [comment] 2019-06-21 19:42
Unfortunately, Combo control only supports a list of strings as the source and we are sorry for any inconvenience caused by this.

I can suggest below approach which may mitigate the issue a little bit:

        const items = [
            { id: "item-1", text: "Item 1" },
            { id: "item-2", text: "Item 2" },
            { id: "item-3", text: "Item 3" }, 
            { id: "item-5", text: "Item 5" }, 
            { id: "item-4", text: "Item 4" },
            { id: "item-6", text: "Item 6" },
            { id: "item-10", text: "Item 10" },
            { id: "item-7", text: "Item 7" }, 
            { id: "item-8", text: "Item 8" }, 
            { id: "item-9", text: "Item 9" }
        ];

        const comboOptions = <Combos.IComboOptions>{
            width: "400px",
            source: items.map(i => i.text),
            change: (combo?: Combos.Combo) => {
              const index = combo.getSelectedIndex();
              if (index >= 0) {
                  console.log(JSON.stringify(items[index]));
              }
           }
        };
          
        Controls.create(Combos.Combo, container, comboOptions);

Thanks

**Comment by chcomley** [comment] 2019-06-21 20:11
@danielstefanescu, @mongeon, @froens, Per the previous comment, which suggests that Combo control only supports a list of strings as the source, and suggests an approach which may mitigate, I'll be closing this issue. If you have any more questions about our docs, or the information contained within, please do create another issue. Thank you all for your feedback.

**Closed by chcomley** 2019-06-21 20:11 UTC
Labels: area - extend, devops/prod, doc-bug, help wanted
