### ISSUE TITLE
Adding Git branches to code search indexing is _not_ available in AzDOS 2019u1

### ISSUE THREAD

**Issue by TASlavens** [MicrosoftDocs/vsts-docs#6716] opened 2019-12-18 00:34 UTC
When viewing the document for the Azure DevOps Server 2019 version, in the section "Syntax for simple and compound searches", the paragraph right before the image showing how to configure code search for additional branches other than "master" in a Git repo, and also the entire paragraph itself, does not apply to AzDOS 2019.  The option to add branches for indexing is not present in AzDOS 2019u1 (I'm looking right at the options page in another browser), and according to the release notes for update 1.1, that capability has not yet been added.  This documentation error is confusing for developers; please correct it soon.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12512a47-a85e-736e-9045-3004b4459d95
* Version Independent ID: c7a4b27e-5b68-1e07-527c-cb357eb53b3b
* Content: [Use advanced code search options - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/project/search/advanced-code-search-syntax?view=azure-devops-2019)
* Content Source: [docs/project/search/advanced-code-search-syntax.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/search/advanced-code-search-syntax.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by ShubhamJain1992** [comment] 2019-12-31 05:57
Hi TASlavens,
Search in Azure DevOps Server 2019 Update 1 does support indexing up to 5 branches. Can you please provide me the steps you tried to add branches and the release notes you referred which says that this is not supported. 

Thanks,
Shubham Jain

**Comment by TASlavens** [comment] 2019-12-31 18:47
Hi, @ShubhamJain1992 -  It looks like I was mistaken, although I would say that the UX for search mislead both me and the developer who reported this behavior to me.

I was referring to the instructions at https://docs.microsoft.com/en-us/azure/devops/project/search/advanced-code-search-syntax?view=azure-devops-2019#syntax-for-simple-and-compound-searches as illustrated in the screen capture there.  One of our developers reported that a search of the form "this_text repo:some_git_repo" was failing, and I was unaware that the Git repo in question is a forked repo.  Searching isn't supported for Git forked repos, which is plainly documented, and the UX icons are different for Git forked repos, but the search results do not show the Git repo icon - I didn't think to check that.

However, the search UI shouldn't have provided the link "Include/exclude searchable branches" for a Git forked repo (in the doc image that link is "Configure searchable branches" instead).  When I clicked that link from the empty search results, I landed on the configuration page for the forked repo, which of course did not have any way to add branches, because it is not searchable in the first place.

So, in summary, I was incorrect about the feature being missing - it is present for Git repos which are not forked repos.  However, the search results should not provide a misleading link to add searchable branches on a forked repo which cannot be searched at all.  That's clearly not a documentation problem, but rather a deficiency in AzDOS 2019u1 itself.  However, it surely would have been helpful (and saved me some time) if the documentation would reinforce that the link to configure branches, as shown in that image, will be present even if the repo cannot be searched at all.

To clear up other loose ends, I wrote that the addition of the feature was not stated within the update 1.1 release notes, not that the release notes stated that the feature was not present.  In retrospect, it is obvious now that there was no mention of the feature in the update 1.1 release notes simply because the feature was already present; I did not refer to prior release notes.  Additionally, had the status of the report at https://developercommunity.visualstudio.com/content/problem/301421/unable-to-search-for-code-other-than-master-branch.html been updated to reflect that the feature had been added to on-premises AzDOS as well as VSTS, I would have investigated further before filing an incorrect report here, ultimately saving myself (and especially you and perhaps others at MS) some time.

Finally a minor point:  The corresponding AzDOS 2019u1 UX does not look like the referenced screenshot in this doc, so unless the UX changed between 2019u1 and 2019u1.1, it might need to be updated.

Thanks!

**Comment by ShubhamJain1992** [comment] 2020-01-02 04:58
Hi @TASlavens,
The screenshot is not the latest and I have noted the action item to update that.
Regarding the option to include/exclude a branch for a forked repo, I could not understand the possible steps take to reach that option. Search does not index a forked repo, so there should be no results when the forked repository is selected in the repository filter on the search UX page. Hence the branch filter should be disabled and hence the option to configure branches for the forked repo should not be present at all. Can you help me with the steps taken to reach that configuration.
![image](https://user-images.githubusercontent.com/57885721/71652317-888d1a80-2d4a-11ea-8918-05a8d0c9b1e4.png)

**Comment by TASlavens** [comment] 2020-01-02 17:09
@ShubhamJain1992,

To see the behavior I'm describing, it is necessary to explicitly add the forked repo to your search, so to expand your example, "ReadMe repo:some_forked_repo" - note the explicit specification of the forked repo using the "repo:" search syntax.  Of course, forked repos aren't searchable, but the developer who reported the behavior to me did not know that, nor did I at the time.  I would say that the behavior shown in the screenshot from your most recent response is what the result _should_ be when explicitly specifying a forked repo for search, but that is not what happens in 2019u1.  Instead, it still shows me the option to configure branches for search, despite the forked repo being specified.

**Comment by ShubhamJain1992** [comment] 2020-01-05 08:40
@TASlavens,
I tried reproducing the issue in 2019u1 with the repo: filter as well, but could not reach the branch configuration option. Can you share some snapshot and steps for the same. Allowing branch config on forked repo is not the expected behavior so I just want to ensure this don't not trouble anyone.

**Comment by TASlavens** [comment] 2020-01-10 21:26
@ShubhamJain1992 Here's a list of steps with screenshots from our non-production AzDOS 2019u1 instance.  I've kept redactions to a minimum, but some were required by our SOPs.

1. Navigate to a file in any forked Git repo, so for this example, https://_server_/tfs/DefaultCollection/QS/_git/ds-TestProject and select any source file; I happened to choose a Python file, but I think it doesn't matter much

**Comment by ShubhamJain1992** [comment] 2020-01-14 05:15
Thanks @TASlavens, I was able to reproduce the behavior and will work with the team to improve it.

**Comment by ShubhamJain1992** [comment] 2020-01-22 11:20
This has been added to backlog. Since this is not related to docs. I am closing this.

**Comment by KathrynEE** [comment] 2020-02-05 19:27
@chcomley - Assigning this to you.

**Comment by ShubhamJain1992** [comment] 2020-03-11 05:23
Hi,
As discussed changes have been pushed and we will display a message to inform the user that the search is not supported on forked repository when a user tries to. This will be present in the next release.
@chcomley, Can we resolve this issue? The branch configuration is supported and working for normal repos. For Forked repos it is not supported.

**Closed** 2020-03-11 15:24 UTC
Labels: Pri2, devops-collab/tech, devops/prod, doc-bug
