### ISSUE TITLE
Unclear why github is the selected repository

### ISSUE THREAD

**Issue by lukos** [MicrosoftDocs/vsts-docs#5465] opened 2019-09-03 12:56 UTC
I am trying to follow these steps for code that is stored in Azure Devops code but it doesn't work and the Configure tab is not available. It is unclear but I am assuming that for some reason this only works with github, in which case this needs to be made much more clear. If there is no way to build code/Dockerfile from Azure Devops and push it to ACR, then Pipelines is no use for a proper CD process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45ba2ebe-27c4-111b-18b4-0192d8c3fb3a
* Version Independent ID: f48fdf00-e04f-b406-93f3-20b7fad568be
* Content: [Build and push to Azure Container Registry - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/containers/acr-template?view=azure-devops&tabs=java)
* Content Source: [docs/pipelines/ecosystems/containers/acr-template.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/containers/acr-template.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by shashankbarsin** [comment] 2019-10-04 16:47
Unable to reproduce this issue as I just verified that it works for an Azure Repos repository containing Dockerfile as well.

@lukos I think the multistage pipeline preview feature may not be turned on and that's why the Configure tab is not available. Can you turn on the multistage pipeline preview feature and try again. We do have a note (shown below) suggesting to do so in our documentation as well. Closing this issue as a result as this is not an issue with the documentation

![image](https://user-images.githubusercontent.com/4594231/66224888-af5c9600-e6f4-11e9-93e5-3d0cb6362363.png)

**Closed by shashankbarsin** 2019-10-04 16:47 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, doc-bug
