### ISSUE TITLE
Document missing advice if Dashboard Type radio buttons are missing

### ISSUE THREAD

**Issue by JamesMiera** [MicrosoftDocs/vsts-docs#6897] opened 2020-01-11 01:26 UTC
1. Connect to Azure DevOps Services organization
2. Ensure that all Preview Features are enabled
3. Ensure membership in team project and membership as team admin
3. Click New Dashboard
4. Expected: Observe radio buttons for Team Dashboard and Project Dashboard
5. Actual: There are no radio buttons for Team Dashboard or Project Dashboard

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3d9f6cf-89b6-a0e3-0a37-f23446ede457
* Version Independent ID: 988af21a-7ee0-66b4-0fac-07360b8be17d
* Content: [Add, rename, delete, and manage team dashboards - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/dashboards?view=azure-devops#feedback)
* Content Source: [docs/report/dashboards/dashboards.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/dashboards.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by JamesMiera** [comment] 2020-01-13 20:55
Though the documentation is still missing, it is worth noting that the underlying issue may be due to latency on rolling out sprint 162 to the org. Thus, the note might say something like:
`Note: If the Dashboard Type controls are not present, it is possible that the Sprint 162 Upgrade has not yet been applied.`

**Comment by msebolt** [comment] 2020-01-14 06:16
@JamesMiera Thank you for the feedback, it's good to hear the issue is resolved.

Usually notes are only added if the product team has not yet applied a proper fix, but thank you for bringing this to our attention.

@KathrynEE

**Comment by KathrynEE** [comment] 2020-01-23 21:32
@JamesMiera - Thank you for the feedback. It is a good practice to add a note that it can take up to 3 weeks for a new feature to roll out. I will work to add this in the future. Since you opened this issue on 1/13, which is when the new feature was released, I would expect that was the issue. Closing this for now, please feel free to reopen if there is something else to consider.

**Closed by KathrynEE** 2020-01-23 21:32 UTC
Labels: Pri1, devops-analytics/tech, devops/prod, doc-bug
