### ISSUE TITLE
Add missing services

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/vsts-docs#1595] opened 2018-08-24 11:53 UTC
Many new service types are available and should be listed in this page.

Example: Office 365

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dc61b61-ed67-8313-99d4-d736e7f48234
* Version Independent ID: 3e0fcf87-9744-cec8-24f8-9f68371959c6
* Content: [Integrate with service hooks](https://docs.microsoft.com/en-us/vsts/service-hooks/overview?view=vsts)
* Content Source: [docs/service-hooks/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/overview.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment] 2018-09-21 15:29
Closing this as a duplicate of https://github.com/MicrosoftDocs/vsts-docs/issues/1596#event-1839429945

**Closed by elbatk** 2018-09-21 15:29 UTC
