### ISSUE TITLE
How to restrict the REST call response with just one output

### ISSUE THREAD

**Issue by tanmayghosh2507** [MicrosoftDocs/vsts-docs#4009] opened 2019-04-18 16:51 UTC
So, for a custom service connection type, multiple service connection endpoints can be created. Now in the build task picklist, all those endpoint names will be populated in the dropdown. 
Is there any way I can just show only one fixed endpoint or set a default and make it readonly? Or can I add a restriction the service connection, that no one else can create an endpoint?

**Comment by thomps23** [comment] 2019-04-22 20:46
Duplicate of https://github.com/MicrosoftDocs/vsts-docs/issues/4010

**Closed** 2019-04-22 20:46 UTC
Labels: duplicate
