### ISSUE TITLE
How do i find pipelineId of another Pipeline from which i need to download an artifact from?

### ISSUE THREAD

**Issue by sandeepzgk** [MicrosoftDocs/vsts-docs#3263] opened 2019-02-06 22:14 UTC
The documentation at https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&viewFallbackFrom=vsts  states that System.DefinitionId is "The ID of the build pipeline." But that seems to be not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03d67d0-8738-72e6-dbe7-324c1784d4fc
* Version Independent ID: bbb4d774-cd98-3ecb-7ccf-5f49e6f2b425
* Content: [Download Pipeline Artifact task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-pipeline-artifact.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-pipeline-artifact.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **midenn**

**Comment by katlimruiz** [comment] 2019-05-30 22:30
go to Azure Pipelines and open the pipeline you want, and in the url you'll see the definition=382 (or any number you may have). If you look the github of this task, definition is an alias for pipeline.

**Comment by chasewilson** [comment] 2019-06-22 00:37
@sandeepzgk Thank you for the feedback and @katlimruiz thanks for the input! are you still having this issue or does the commented solution answer it?

**Comment by chasewilson** [comment] 2019-06-25 16:52
@sandeepzgk I'll be closing this issue if you don't have any more feedback. Feel free to open a new issue if the issue isn't resolved! Thank you again!

**Closed by chasewilson** 2019-06-25 16:52 UTC
Labels: area - pipelines, devops/prod, doc-bug
