### ISSUE TITLE
Missing information on consuming nuget packages in a YAML pipeline from an Azure Devops Artifact nuget feed

### ISSUE THREAD

**Issue by Paul-Dempsey** [MicrosoftDocs/vsts-docs#3871] opened 2019-04-04 19:53 UTC
I've been banging my heard for days trying to restore packages from an Azure Devops Artifacts nuget feed in a YAML pipeline, but no luck. MSBuild and dotnet restore both just tell me:

    warning : The plugin credential provider could not acquire credentials. ...
     Warning : Unable to load the service index for source  ...

I can't find any information on what the problem is or how to get it to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11ed58a1-5819-f3a4-c674-dafcdbd56fbc
* Version Independent ID: d68aca4d-3fd3-1864-09f5-6060295e0399
* Content: [Publishing to NuGet feeds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/nuget.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **amullans**

**Comment by gtalton** [comment] 2019-04-05 19:21
I could use some guidance on the same topic.

**Comment by elbatk** [comment] 2019-04-12 17:57
Hey people - I'll have some time to take a look at this early next week, as I'm traveling today. We are working on making our services work better (and easier) in YAML, so this will be a good exercise for us.

**Comment by elbatk** [comment] 2019-04-12 17:58
For reference, could you both post a sample of the YAML you're trying to use?

**Comment by Paul-Dempsey** [comment] 2019-04-26 21:17
pool:
  name: Hosted VS2017
  demands: msbuild


steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.9.4'
  inputs:
    versionSpec: 4.9.4

- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK Tool Installer'
  inputs:
    version: 2.2.105

- task: DotNetCoreCLI@2
  displayName: 'DotNet restore packages'
  inputs:
    command: restore
  continueOnError: false

etc to build and publish

**Comment by Paul-Dempsey** [comment] 2019-04-26 21:22
I found a workaround, but according to the docs, it should just work without this:

    - task: NuGetCommand@2
      displayName: 'Authenticate nuget feed'
      inputs:
        command: custom
        arguments: sources update -Name "<feed-name>" -Username "vsts" -Password "$(System.AccessToken)" -StorePasswordInClearText -ConfigFile ./NuGet.Config

**Comment by elbatk** [comment] 2019-07-16 21:50
Hi everyone, this looks like a duplicate of #3884 so I'm going to close this in favor of that one.

**Closed by elbatk** 2019-07-16 21:50 UTC
Labels: devops-cicd/tech, devops/prod
