### ISSUE TITLE
Is there a limitation on the number of pipelines a project can have?

### ISSUE THREAD

**Issue by raisingcode** [MicrosoftDocs/vsts-docs#5619] opened 2019-09-16 16:13 UTC
[Enter feedback here]

Hi currently we're using free tier of azure devops wanted to know if there is a known limit of the number azure pipelines that are allowed for our project.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57f8545-bb15-3a71-1876-3a9ec1a59b93
* Version Independent ID: 28c87c8d-c28d-7493-0c7c-8c38b04fbcd7
* Content: [Run number - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/run-number.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/run-number.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment] 2019-09-17 20:23
@raisingcode Closing this one as a duplicate of https://github.com/MicrosoftDocs/vsts-docs/issues/5620 where the answer is given (no limit on the number of pipelines, just on the number of concurrent running pipelines)

**Closed by steved0x** 2019-09-17 20:23 UTC
Labels: Pri2, devops-cicd/tech, devops/prod, product-question
