### ISSUE TITLE
Why is there no documentation on this task?

### ISSUE THREAD

**Issue by kiranjulapalli** [MicrosoftDocs/vsts-docs#2131] opened 2018-10-17 17:55 UTC
I understand that we need to use a different task instead of this deprecated one. 
However for an already configured legacy task (Copy and Publish Build artifacts), if we want to update to the new tasks (Copy Files and Publish Build Artifacts), how is the user expected to know what the current task is doing under the hood (with no documentation)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34301e0e-fc7e-bf7a-de61-c466756f22a3
* Version Independent ID: 2595a9cf-03b2-4206-6dda-43ac1b903add
* Content: [Copy and publish build artifacts - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-and-publish-build-artifacts?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/copy-and-publish-build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/copy-and-publish-build-artifacts.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment] 2018-10-18 16:28
@kiranjulapalli could you be a bit more specific about what details you're looking for, and on which task?

**Comment by kiranjulapalli** [comment] 2018-10-18 20:44
@andyjlewis If you go to the original documentation link https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-and-publish-build-artifacts?view=vsts you would see that all it says is this task is deprecated. It has no info on the actual functionality of this task.

**Comment by kvishnuthej777777** [comment] 2018-10-19 06:15
@andyjlewis i am getting Error: File upload failed even after retry intermittently using this [deprecated], please provide us with documentation of new Task that we can use

**Comment by andyjlewis** [comment] 2018-10-19 11:05
Thank you both for raising and elaborating on these issues.

@kiranjulapalli you can still see the docs for the Copy and publish build artifacts task by changing the version selector in the upper-left corner, or just click this link: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-and-publish-build-artifacts?view=tfs-2015

@kvishnuthej777777 the hub of the docs for the newer tasks is here: https://docs.microsoft.com/en-us/azure/devops/pipelines/build/artifacts. This topic explains how you use the newer tasks to publish artifacts.

Looking at the topics I think at least part of the cause for confusion. We've been linking to this topic from the newer topic. Also, we recently manually added version info below the title of all our Pipeline topics. This task was erroneously marked as supporting TFS 2017 and newer. I've got an internal PR that fixes this and I hope reduces the confusion.

**Closed by andyjlewis** 2018-10-19 11:05 UTC
