### ISSUE TITLE
web hooks queueing order?

### ISSUE THREAD

**Issue by bitsofinfo** [MicrosoftDocs/vsts-docs#7647] opened 2020-03-19 17:27 UTC
So i have a web hook configured, but noticing that the git events are "queued" but emit out of order. 

What is the ordering of events that are emitted by service hooks?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96287641-3e4f-b038-148f-08e8471bd573
* Version Independent ID: b0034cd1-4f29-2e2d-c2bb-49004552dae8
* Content: [Troubleshoot your service hooks integrations - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/service-hooks/troubleshoot?view=azure-devops)
* Content Source: [docs/service-hooks/troubleshoot.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/troubleshoot.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by WilliamAntonRohm** [comment] 2020-03-19 23:53
Duplicate of #7646.

**Closed by WilliamAntonRohm** 2020-03-19 23:53 UTC
Labels: Pri2, devops-collab/tech, devops/prod
