### ISSUE TITLE
blocked by "_RequestVerificationToken" 

### ISSUE THREAD

**Issue by ebmarquez** [MicrosoftDocs/vsts-docs#3198] opened 2019-01-31 20:25 UTC
I get the following error.  I checked an my browser does have cookies enabled on (IE, Edge, and Chrome). I've also cleared my cookies but the error persists.

The required anti-forgery form field "__RequestVerificationToken" is not present. Ensure that cookies are enabled in your browser.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64e85ff9-9add-d15c-e92f-02d7dd05e0f2
* Version Independent ID: 0cbd7427-6acd-3cfc-1a3b-8bf5ca60f3bd
* Content: [Connect to your Git repos with SSH - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azdevops)
* Content Source: [docs/repos/git/use-ssh-keys-to-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/use-ssh-keys-to-authenticate.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by vjinma** [comment] 2019-01-31 20:56
I'm also receiving this error when I try to add a SSH public key.  This functionality was working fine last week.

**Comment by steved0x** [comment] 2019-02-04 19:44
@ebmarquez @vjinma The product team is tracking this and it looks like a fix has been deployed. Here is the issue where they are tracking this:

https://developercommunity.visualstudio.com/content/problem/441515/unable-to-add-public-ssh-key.html

If the issue is still not resolved for you, please reply to that thread there and let them know.
Thank you for letting us know and sorry for the trouble.

**Closed by steved0x** 2019-02-04 19:44 UTC
Labels: devops/prod, repos
