### ISSUE TITLE
PowerShell Encoding Error

### ISSUE THREAD

**Issue by AaronGomezBHGE** [MicrosoftDocs/vsts-docs#6881] opened 2020-01-10 01:24 UTC
At end of step 1 it says to set the samplestring env to "Human".

When I try this I get the following error:

PS E:\dev\git\integerVersionChecks\buildAndReleaseTask&gt; $env:INPUT_SAMPLESTRING = "Human"
PS E:\dev\git\integerVersionChecks\buildAndReleaseTask&gt; node index.js
##vso[task.debug]agent.TempDirectory=undefined
##vso[task.debug]agent.workFolder=undefined
##vso[task.debug]loading inputs and endpoints
##vso[task.debug]loading INPUT_SAMPLESTRING
##vso[task.debug]loaded 1
##vso[task.debug]Agent.ClientCert=undefined
##vso[task.debug]Agent.SkipCertValidation=undefined
##vso[task.debug]task result: Failed
##vso[task.issue type=error;]The argument 'encoding' is invalid for data of length 5. Received 'hex'
##vso[task.complete result=Failed;]The argument 'encoding' is invalid for data of length 5. Received 'hex'

What's weird is that if I make samplestring an even number of letters it works.  If I make the value "Humann" it works.   Any idea what's happening here or what I would need to do to make this work exactly as shown?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a Build or Release Task - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-build-task.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment] 2020-01-10 18:19
@AaronGomezBHGE Thank you for the feedback, assigning this to the author for review.

**Comment by damccorm** [comment] 2020-01-14 22:06
Hm, I'm not able to reproduce. With that said, this is almost definitely due to an encoding issue with how we store values when using the task-lib - https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/vault.ts#L10. It looks like somehow your encoding is non-utf8 (Node default) - I'm not sure how that happened, but the issue will almost definitely not manifest on our agents where we explicitly set the encoding.

A couple things you could try to work around this locally:
1) call `chcp 65001` before execution
2) Try executing it from cmd instead of powershell

**Comment by chcomley** [comment] 2020-01-15 18:01
Thanks for your help, @damccorm. @AaronGomezBHGE, please @mention damccorm if you have any further questions, thank you.

**Closed** 2020-01-15 18:01 UTC
Labels: Pri1, devops-ecosystem/tech, devops/prod, doc-bug

**Comment by BMuuN** [comment] 2020-02-06 19:30
@AaronGomezBHGE and for anyone else that lands here due to the error "The argument 'encoding' is invalid for data of length 5. Received 'hex'"...

I ran into this error earlier today whilst debugging my own Azure Dev Ops extension and found it's related to the latest version of Node.Js v13.7.0.  To fix my error I uninstalled v13.7.0 and installed v12.4.1 which is the same version of Node.Js that's running on Azure DevOps.
