### ISSUE TITLE
Firewall rules for accessing repos via SSH

### ISSUE THREAD

**Issue by tomw-ucb** [MicrosoftDocs/vsts-docs#4314] opened 2019-05-23 12:55 UTC
Hi MS team, 

It would be great to have the firewall rule specifications (ports and domains) in order to access Azure repositories over SSH ( or even HTTPS ).

Please keep in mind that the domain name in the clone SSH URL from the DevOps portal (vs-ssh.visualstudio.com) is load balanced to other domain names.

Thanks in advance, Tom

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e59bebc3-fe8a-ad9e-7c55-884a8c7b4bac
* Version Independent ID: 7db3d604-b118-2f7b-85f4-1bd52244b279
* Content: [Build source repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/?view=azure-devops)
* Content Source: [docs/pipelines/repos/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by congyiwu** [comment] 2019-09-16 18:50
This looks like a dupe of #5460, which was fixed recently

**Comment by congyiwu** [comment] 2019-09-16 18:51
@steved0x can you close this?  I don't have permission to.

**Comment by tomw-ucb** [comment] 2019-09-16 19:01
Hi @congyiwu,

A white list of IP ranges is not the answer to my request.
But for sure it useful information that could be added this page too.

KR, Tom

**Comment by congyiwu** [comment] 2019-09-16 19:06
https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops currently says:

> If you need to connect to Git repositories on Azure DevOps with SSH, you need to allow requests to port 22 for the following:
> ssh.dev.azure.com
> ssh.visualstudio.com
> All IP addresses in the "name": "AzureCloud" section of [this file](https://www.microsoft.com/en-us/download/details.aspx?id=56519) (updated weekly): Azure IP ranges and Service Tags - Public Cloud.

That includes both the ports and domains for SSH. Is there something else you're asking for?

**Comment by tomw-ucb** [comment] 2019-09-16 19:21
Then a reference to this page on this content page, would be handy.
I will forward this information to our network team.

**Comment by congyiwu** [comment] 2019-09-16 19:37
Ah, I agree something should be done to make it easier to find the SSH firewall rules.

**Comment by justhchung** [comment] 2019-12-13 18:40
Thank you for your feedback. 
We are closing this issue as there is no action to take on our part to address the issue.  The guidance provided is correct.

**Closed by justhchung** 2019-12-13 18:40 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
