### ISSUE TITLE
Intermediate outputs from stages

### ISSUE THREAD

**Issue by IdiotLeon** [MicrosoftDocs/vsts-docs#3675] opened 2019-03-18 18:07 UTC
Where to save the output from previous stages, which I can apply in latter stages?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Release variables  and debugging - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment] 2019-03-18 18:46
This is a duplicate of https://github.com/MicrosoftDocs/vsts-docs/issues/3674. Closing it for that reason.

**Closed by alexhomer1** 2019-03-18 18:46 UTC
