### ISSUE TITLE
PDF is out-of-date

### ISSUE THREAD

**Issue by Rick-Kirkham** [MicrosoftDocs/vsts-docs#6320] opened 2019-11-10 21:57 UTC
The version of this page in the PDF is out-of-date. For example, it says that page titles cannot have blank spaces; but this HTML version doesn't include this restriction in the table of restrictions. Can you please rebuild the PDF for those of us that need it? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7892ee5-8b56-bd95-29bb-41ebb8a8bd7e
* Version Independent ID: eccf0785-0968-d6a2-d29e-0c4796aa165c
* Content: [Add, edit, reorder and manage wiki pages in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/add-edit-wiki?view=azure-devops&tabs=browser)
* Content Source: [docs/project/wiki/add-edit-wiki.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/add-edit-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment] 2019-11-11 19:20
@Rick-Kirkham  Thank you for the feedback.

Unfortunately, I cannot find the example you provided.  The PDF I downloaded seems to contain the statement on blank characters:

![Capture](https://user-images.githubusercontent.com/6675884/68614072-07fe1c00-0475-11ea-82f7-de529e79a4f9.PNG)

Can you add further specifics or include another example?

**Comment by msebolt** [comment] 2019-11-14 07:11
Closing the issue now, please comment below if there are any issues.

**Comment by Rick-Kirkham** [comment] 2019-11-14 16:09
You have reproduced the issue! The PDF has the restriction, but the HTML version doesn't have this restriction! There's no such restriction any more. Please reopen this and fix the PDF.

**Comment by Rick-Kirkham** [comment] 2019-11-14 16:10
Also, there's something wrong with the notification system. I didn't receive an email from your comment 3 days ago.

**Comment by msebolt** [comment] 2019-11-14 16:24
Sorry, but I still can't reproduce...

This image was taken from the site:

![Capture](https://user-images.githubusercontent.com/6675884/68875212-48e57300-06b7-11ea-8dda-97b8e929a86e.PNG)

...and this from the PDF:

![Capture2](https://user-images.githubusercontent.com/6675884/68875219-4b47cd00-06b7-11ea-8627-1a75257140de.PNG)

Is the version selector in the top left-hand corner set to **Azure DevOps Services**?  Please attach a sample of the problem.

For help on GitHub notifications, see [receiving notifications](https://help.github.com/en/github/receiving-notifications-about-activity-on-github/about-email-notifications).

**Comment by Rick-Kirkham** [comment] 2019-11-14 16:43
That page on the site has changed since I created this. The reason I know this is that a second problem, that I did not mention is fixed too. (The table of restrictions appeared twice, once where it is now, and then again just below the table of special characters. The wording in the Restriction column was slightly different in the two versions of the table.) 

At any rate, the restriction about blank characters is not true. Here is a screenshot of a wiki with page titles that have spaces. My speculation is that someone corrected this recently, but the page got messed up somehow (the table appearing twice) and then someone fixed the mess by reverting to an old version with the obsolete restriction on blank characters.
(To answer your question: Yes, **Azure DevOps Services** is in the drop down. )

I think you need to update the page to remove the restriction on blank spaces and then regenerate the PDF.

![image](https://user-images.githubusercontent.com/9088056/68876725-c8744180-06b9-11ea-9575-c815f5826e03.png)

**Comment by msebolt** [comment] 2019-11-14 16:55
I see, no problem, thank you for the providing the details.

Assigning this to the author for review.

**Comment by Rick-Kirkham** [comment] 2019-11-14 17:01
I see now that that table of restrictions is in an [!include]. The include has two monikers, with slightly different versions of the table in each. What I was seeing last week was both versions. In other words, there was a bad build and the monikers were being ignored.

**Comment by chcomley** [comment] 2019-11-14 23:26
Hi @Rick-Kirkham, I've published an update, which should go live shortly today. You're right, you can add a wiki title with spaces, as I did it myself. I'm following up with one of my PMs on the tfs-2018 versioning, as it states "**Titles of pages added offline** must not contain a blank space."  I'll update accordingly once I've connected with the PM. Thanks so much for your contribution!

**Closed** 2019-11-15 00:55 UTC
Labels: Pri1, devops-collab/tech, devops/prod, doc-bug
