### ISSUE TITLE
Why did the crappy YAML agent image names start showing up in build pipelines?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#5828] opened 2019-10-02 17:42 UTC
I've been asked at least three times in the last few days as to which to pick because ONLY ONE OF THE CHOICES MENTIONS A VISUAL STUDIO VERSION in the YAML name. .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thejoebourneidentity
* Microsoft Alias: **jobourne**

**Comment by msebolt** [comment] 2019-10-02 17:57
@StingyJack  Thank you for the feedback.

This would be a good question for the image team, unfortunately we're unable to address this.

Please transfer the issue to the [azure-pipelines-image-generation repo](https://github.com/Microsoft/azure-pipelines-image-generation/issues).

**Comment by StingyJack** [comment] 2019-10-02 18:15
@msebolt - I opened an issue over there, reporting it as a bug. If it isnt a bug, then this docs page needs updating asap.

**Comment by msebolt** [comment] 2019-10-02 18:21
Sounds good, then I'll assign this to the author in the interim.

**Closed** 2019-10-11 13:22 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, product-feedback

**Comment by StingyJack** [comment] 2019-10-11 21:25
@thejoebourneidentity please explain.

**Comment by StingyJack** [comment] 2019-10-14 19:58
@msebolt - This got closed with no information added to it. I would assume then that the docs are correct and that a bug exists somewhere in the pipelines that will be getting fixed so the better names are present. Please confirm.

**Comment by msebolt** [comment] 2019-10-14 22:12
@StingyJack The change above only reflects the most recent list of images, to get the names changed please try the [azure-pipelines-image-generation](https://github.com/Microsoft/azure-pipelines-image-generation/issues) repo.

**Comment by thejoebourneidentity** [comment] 2019-10-18 16:41
The YAML image names showing up in the classic editor is by design. We've made some infrastructural changes that make it much easier to add images later, but this architecture also required that the `agent specification` names are aligned to the YAML labels.

**Comment by StingyJack** [comment] 2019-10-20 20:41
So yall added a more confusing and generally worse user experience _by design_. 

Or was this just another oversight?

>  this architecture also required that the agent specification names are aligned to the YAML labels

"My users hate it when I have to use row IDentity values instead of the user friendly names they used to see in my programs, but I just tell them "the architecture requires this". They will figure out what products 6646 and 443 are eventually and hopefully memorize them so I dont get a bunch of support tickets to go look them up.  They will never understand how important it is that this design is upheld and kept pristine"

Hopefully that sarcasm story helps drive home the point of how dumb it is to use inconsistent and incomplete descriptors when better ones were already available. 

Users dont care about your (or my) attempts at perfection in engineering. We can have our (pointless) attempts, but they need to not interrupt continuity for those who actually pay money for the program, or they may just stop paying for them.
