### ISSUE TITLE
Deploy pull request job not working and is skipped in deploy stage

### ISSUE THREAD

**Issue by pretty25** [MicrosoftDocs/vsts-docs#7878] opened 2020-04-09 13:08 UTC
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by pretty25** [comment] 2020-04-09 13:11
![image](https://user-images.githubusercontent.com/11729130/78898439-b67dab80-7a6b-11ea-9ee0-51b08c0c4931.png)

![image](https://user-images.githubusercontent.com/11729130/78898464-c2696d80-7a6b-11ea-9cd1-f669123a9de0.png)


just want to check is this expected to skip as part of this https://docs.microsoft.com/en-gb/azure/devops/pipelines/ecosystems/kubernetes/aks-template?view=azure-devops excerise / lab ?

**Comment by steved0x** [comment] 2020-04-09 15:16
Closing as duplicate of https://github.com/MicrosoftDocs/vsts-docs/issues/7879, thank you for filing it there.

**Closed by steved0x** 2020-04-09 15:16 UTC
Labels: Pri3
