### ISSUE TITLE
How do I get my work items into a backlog

### ISSUE THREAD

**Issue by brucedkyle** [MicrosoftDocs/vsts-docs#7651] opened 2020-03-19 22:47 UTC
I have imported my work items. But I must be missing something. How do I get my work items to appear in my Backlog?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8753a98e-77ca-265d-d5e3-91a4b1319e5e
* Version Independent ID: bed9697d-3bea-3202-0bf1-80f37aea0286
* Content: [Plan product backlog of stories, issues, & more - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/create-your-backlog?view=azure-devops&tabs=agile-process)
* Content Source: [docs/boards/backlogs/create-your-backlog.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/create-your-backlog.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment] 2020-03-19 23:57
Duplicate of #7650.

**Closed by WilliamAntonRohm** 2020-03-19 23:57 UTC
Labels: Pri1, cba, devops-agile/tech, devops/prod, duplicate
