### ISSUE TITLE
Runtime expressions do not create boolean variables

### ISSUE THREAD

**Issue by peter-bloomfield** [MicrosoftDocs/vsts-docs#6970] opened 2020-01-17 09:29 UTC
The documentation isn't clear about the data type resulting from runtime expressions.

For example, I tried to define a boolean variable indicating whether the current build is based on the master branch:

```
variables:
  - name: isMasterBuild
    value: $[ eq(variables.Build.SourceBranch, 'refs/heads/master') ]
```

From the documentation, I assumed "isMasterBuild" would be a boolean variable, allowing it to be used directly in a condition like this:

```
jobs:
  - job: MasterOnly
    condition: variables.isMasterBuild
    ...
```

However, "isMasterBuild" turned out to be a string containing "True" or "False". The casting rules dictate that all non-empty strings are converted to boolean true, meaning the job always gets executed.

The workaround I've found is to do an explicit string comparison in the condition:

```
    condition: eq(variables.isMasterBuild, 'True')
```

It seems like the variable should be boolean so I suspect this is a bug. Either way, it would be helpful to clarify the behaviour in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment] 2020-01-18 01:24
@peter-bloomfield Thank you for providing feedback to Microsoft, assigning this to the author for further review.

Please submit any design features and/or related bugs to the product team [here](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by juliakm** [comment] 2020-03-05 15:05
@peter-bloomfield  All variables are strings. As a result, when you use a variable, it will be output as a string. We are going to work on making this clearer in the documentation. If you want to use typed values, you should use parameters. Here's more information on [using parameters in pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops).

**Closed** 2020-03-09 13:30 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement

**Comment by tomasfejfar** [comment] 2022-05-06 08:41
Is there a way to convert the boolean false result of an expression to an empty string that would be evaluated as boolean false in the condition? 

I prepared following "mock":
```
EMPTY: ''
SHOULD_BE_FALSE: $[or(variables.EMPTY, variables.EMPTY)]
// ... 

echo SHOULD_BE_FALSE=$(SHOULD_BE_FALSE)
// SHOULD_BE_FALSE=False
``` 
🎉 

But the problem is now how to convert `False` to `''`

**Comment by tomasfejfar** [comment] 2022-05-06 09:49
Just in case someone stumbles here, this is the solution I used in the end. It's overly verbose, complicated and stupid, but it seems to be the only way how to make it work. 

```
variables:
  IS_MASTER: >-
    $[
      replace(
        eq(variables['Build.SourceBranchName'], 'master'),
        False,
        ''
      )
    ]
```
This results in variable IS_MASTER, that is either `"True"` or `""`. Therefore you can use it directly in condition:
```
  - task: AmazonWebServices.aws-vsts-tools.ECRPushImage.ECRPushImage@1
    displayName: 'Push built image as build image'
    condition: variables.IS_TAG_OR_MASTER
```
There is a small caveant when using the variable outside of pipelines context in bash for example. Interpolating empty string is the same as not having it there at all. Unfortunatelly converting the variable to `0` instead of empty string wouldn't work in Pipelines. Therefore you need to have a separate variable for using in script:
```
 BUILD_NODE: >-
    $[
      replace(
        replace(
          eq(variables.IS_MASTER,'True'),
          True,
          1
        ),
        False,
        0
      )
    ]
```
This results in a variable `BUILD_NODE` that is either `"0"` or `"1"`. That can be used like this:
```
- script: runSome.sh $(BUILD_NODE)
# runSome.sh 0
```
Below is the behavior without the conversion:
```
- script: runSome.sh $(BUILD_NODE)
# runSome.sh
# runSome.sh: : line 4: 2: unbound variable
```

Credit goes to the Stackoverflow answer: https://stackoverflow.com/a/67198023/112000
