### ISSUE TITLE
"Docker" is not an option in the Configure step

### ISSUE THREAD

**Issue by revodavid** [MicrosoftDocs/vsts-docs#4670] opened 2019-06-27 21:02 UTC
Once the Configure tab in the steps above, "Docker" is not listed as an option. Only "Starter pipeline" and "Existing Azure Pipelines YAML file" are offered by default, and "Docker" is not a member of the list that appears when you click "show more".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45ba2ebe-27c4-111b-18b4-0192d8c3fb3a
* Version Independent ID: f48fdf00-e04f-b406-93f3-20b7fad568be
* Content: [Build and push to Azure Container Registry - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/acr-template?view=azure-devops#create-a-container-registry)
* Content Source: [docs/pipelines/languages/acr-template.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/acr-template.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by shashankbarsin** [comment] 2019-07-03 10:28
@revodavid, the Docker template recommendation is made if a Dockerfile is found in the repo to which the pipeline is being created for. Did you connect your repo to the sample repo mentioned in the doc?([MicrosoftDocs/pipelines-javascript-docker](https://github.com/MicrosoftDocs/pipelines-javascript-docker)). If you were trying to connect your pipeline to a repo containing Dockerfile, but still didn't get the Docker template recommendation, I'll suggest opening an issue on [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). Closing this issue now as this is not a bug in the documentation content.

**Closed by shashankbarsin** 2019-07-03 10:28 UTC
Labels: doc-bug
