### ISSUE TITLE
Windows Service Misnamed

### ISSUE THREAD

**Issue by LanceMcCarthy** [MicrosoftDocs/vsts-docs#2910] opened 2019-01-03 22:27 UTC
Currently the documentation states the service will be listed as `Azure Piplines Agent`. This **is not** true, as of the latest version of the agent (in Jan 2019). I see "VSTS Agent (my agent name)" in my Services list.

This caused me to start, restart, uninstall and reinstall a few times because I thought the agent wasn't running. A couple hours of wasted time.

I recommend adding both possible names for now, at least until you're 100% sure that it will always be "Azure Pipelines Agent" :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a build and release agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=vsts)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by nschonni** [comment] 2019-01-03 23:36
Duplicate of #2885

**Comment by awentzel** [comment] 2019-02-28 22:07
The point of self-hosting feels appropriate for those that want scale and reliability.  It's terrible idea to run a build agents under your desk and this seems to be the focus of the documentation on this page. Why is there no information on setting up 4 build agents for a production environment rather than running under someone's desk. 

Self-hosted Linux agent does this.  Even though there the commands are mixed and confusing when running between platforms.  run `./config.sh --help` and see all the special notes about different platforms.  This just isn't useful, scalable, or maintainable.  Directions don't even work for Ubuntu 18.04. You just can't get the service to run.

**Comment by vtbassmatt** [comment] 2019-03-15 11:51
Agree, dupe of 2885 (and I've addressed it in an upcoming PR).

**Closed by vtbassmatt** 2019-03-15 11:51 UTC
Labels: pipelines
