### ISSUE TITLE
Typo in pipelines/release/variables.md

### ISSUE THREAD

**Issue by Monnick** [MicrosoftDocs/vsts-docs#4217] opened 2019-05-14 07:59 UTC
Typo in the line 274 (part for ```view the current values of all variables```):
instead: Open the pipelines view of __thr__ summary for the
should be: Open the pipelines view of __the__ summary for the

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Release variables and debugging - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by iamsrivatsa** [comment] 2019-10-11 06:42
The issue is already fixed. Please check!

**Comment by chasewilson** [comment] 2019-10-18 04:36
The documentation has been updated and I'll be closing the issue. Thank you for the feedback and feel free to open a new issue if you have any more feedback.

**Closed by chasewilson** 2019-10-18 04:36 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-bug
