### ISSUE TITLE
Setting variables in macOS fails

### ISSUE THREAD

**Issue by Blightysoft** [MicrosoftDocs/vsts-docs#6168] opened 2019-10-28 19:54 UTC
This line:

echo "##vso[task.setvariable variable=sauce]crushed tomatoes"

Does not work to alter the 'sauce' variable. Nor does:

##vso[task.setvariable variable=sauce]crushed tomatoes

Although it is frankly a lot more believable as a solution. This page also talks about 'shell' and 'batch', but the only similar task in Azure is 'command'. So it seems quite out of date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=classic%2Cshell)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment] 2019-10-29 05:36
@Blightysoft  Thank you for the feedback, assigning this to the author for review.

**Comment by macjustice** [comment] 2019-11-18 21:42
I'm seeing the same behavior on a MacOS host.

**Comment by damccorm** [comment] 2019-12-13 18:24
@Blightysoft this is working for me - see my repro here - https://dev.azure.com/damccorm-repros/mac-os-set-variable/_build/results?buildId=305&view=results.

Any chance you could share a yaml snippet that isn't working for you?

**Comment by damccorm** [comment] 2019-12-14 00:20
I'm going to close since I can't reproduce. Please comment if you still think this is a problem

**Closed by damccorm** 2019-12-14 00:20 UTC
Labels: Pri1, devops-cicd/tech, devops/prod, doc-enhancement
